export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";

//WISHLISTS
export const GET_WISHLISTS = "GET_WISHLISTS";
export const CREATE_WISHLIST = "CREATE_WISHLIST";
export const UPDATE_WISHLIST = "UPDATE_WISHLIST";
export const DELETE_WISHLIST = "DELETE_WISHLIST";

//USER
export const GET_USERS = "GET_USERS";

//PAYMENTMETHOD
export const GET_PAYMENTMETHODS = "GET_PAYMENTMETHODS";
export const CREATE_PAYMENTMETHOD = "CREATE_PAYMENTMETHOD";

//FRIEND
export const GET_FRIENDS = "GET_FRIENDS";
export const CREATE_FRIEND = "CREATE_FRIEND";
export const DELETE_FRIEND = "DELETE_FRIEND";

//WISHLISTCATEGORY
export const GET_WISHLISTCATEGORIES = "GET_WISHLISTCATEGORIES";
export const CREATE_WISHLISTCATEGORY = "CREATE_WISHLISTCATEGORY";
export const UPDATE_WISHLISTCATEGORY = "UPDATE_WISHLISTCATEGORY";
export const DELETE_WISHLISTCATEGORY = "DELETE_WISHLISTCATEGORY";

//LOADER
export const LOADER = "LOADER";
